baseURL = "https://a11y2020.com"
languageCode = "en-us"
title = "Accessibility & Usability 2020"
theme = "blnk"
[outputFormats]
  [outputFormats.slide]
    mediaType = "text/html"
    name = "slide"
    path = "slides"
    isHTML = "true"
[outputs]
  home = ["HTML", "slide"]
  page = ["HTML", "slide"]
  post = ["HTML", "slide"]
[params]
  author = "Simon Borer"
  description = "2020 Humber Accessibility/Usability Course"