baseURL = "https://a11y2020.com"
languageCode = "en-us"
title = "Accessibility & Usability 2020"
theme = "blnk"
[outputFormats]
  [outputFormats.slide]
    mediaType = "text/html"
    name = "slide"
    path = "slides"
    isHTML = "true"
[outputs]
  home = ["HTML", "slide"]
  page = ["HTML", "slide"]
  post = ["HTML", "slide"]
[params]
  author = "Simon Borer"
  description = "2020 Humber Accessibility/Usability Course"
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false